#!/bin/sh


# Replace with your pCloud username and password

PUSR=Username

PPW=Password



# command to startup pcloud and authenticate
rm /root/credentials
echo $PPW | pcloudcc -u $PUSR -p -s -n
PPW=""
PUSR=""
tail -f /dev/null

